development:
  adapter: postgresql
  database: deployment-lab_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: deployment-lab_test
  host: localhost
  min_messages: warning
  username: